// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TauLuftAspire.ApiService.Database;

#nullable disable

namespace TauLuftAspire.ApiService.Migrations
{
    [DbContext(typeof(TauLuftDbContext))]
    partial class TauLuftDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TauLuftAspire.Model.Entity.Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("HumInsideOffset")
                        .HasColumnType("double precision");

                    b.Property<double>("HumOutsideOffset")
                        .HasColumnType("double precision");

                    b.Property<double>("Hysrerese")
                        .HasColumnType("double precision");

                    b.Property<int>("Interval")
                        .HasColumnType("integer");

                    b.Property<double>("MinTempInside")
                        .HasColumnType("double precision");

                    b.Property<double>("MinTempOutside")
                        .HasColumnType("double precision");

                    b.Property<double>("TargetDelta")
                        .HasColumnType("double precision");

                    b.Property<double>("TempInsideOffset")
                        .HasColumnType("double precision");

                    b.Property<double>("TempOutsideOffset")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Config");
                });

            modelBuilder.Entity("TauLuftAspire.Model.Entity.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<bool>("HaveRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LogEntry");
                });

            modelBuilder.Entity("TauLuftAspire.Model.Entity.Measurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsFanRunning")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Inside", "TauLuftAspire.Model.Entity.Measurement.Inside#SingleMeasurement", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("DewPoint")
                                .HasColumnType("double precision");

                            b1.Property<double>("Humidity")
                                .HasColumnType("double precision");

                            b1.Property<double>("Temperature")
                                .HasColumnType("double precision");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Outside", "TauLuftAspire.Model.Entity.Measurement.Outside#SingleMeasurement", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("DewPoint")
                                .HasColumnType("double precision");

                            b1.Property<double>("Humidity")
                                .HasColumnType("double precision");

                            b1.Property<double>("Temperature")
                                .HasColumnType("double precision");
                        });

                    b.HasKey("Id");

                    b.ToTable("Measurement");
                });
#pragma warning restore 612, 618
        }
    }
}
